FROM python:3.9

WORKDIR /usr/app

COPY requirements-dev.txt .
RUN pip install --disable-pip-version-check -r requirements-dev.txt

COPY requirements.txt .
RUN pip install --disable-pip-version-check -r requirements.txt

COPY . .

CMD ./wait-for-it.sh storage:3306 -t 300 && \
    python manage.py migrate && \
    python manage.py collectstatic --noinput && \
    python manage.py runserver ${DJANGO_HOST}:${DJANGO_PORT}